version: '3.3'

services:
  openvpn:
    build: ./server
    volumes:
      - ./server/server.conf:/etc/openvpn/server.conf:Z,ro
      - ./volumes/certs/pki/ca.crt:/etc/openvpn/pki/ca.crt:Z,ro
      - ./volumes/certs/pki/dh.pem:/etc/openvpn/pki/dh.pem:Z,ro
      - ./volumes/certs/pki/private/server.key:/etc/openvpn/pki/server.key:Z,ro
      - ./volumes/certs/pki/issued/server.crt:/etc/openvpn/pki/server.crt:Z,ro
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN                  # when running on newer docker versions
    #privileged: true               # when running on older docker versions
    restart: unless-stopped
